/* HorseFil — recipes, shopping lists, knowledge base and FAQ. */

const RECIPES = [
  /* Phase 1 */
  { phase:1, name:'Morning Nitric Kickstart', time:'4 min', why:'Beet nitrates convert to nitric oxide over 90 minutes — the same pathway ED medication amplifies.',
    ingredients:['1 medium raw beet, peeled and chopped','1 green apple','Thumb of ginger','Juice of half a lemon','200ml cold water'],
    steps:['Blend everything for 45 seconds.','Strain if you prefer it thin.','Drink on an empty stomach, before coffee.'] },
  { phase:1, name:'Anti-Inflammatory Breakfast Bowl', time:'6 min', why:'Omega-3s and polyphenols in one meal, with no blood sugar spike to undo them.',
    ingredients:['3 eggs','Handful of spinach','Half an avocado','1 tbsp olive oil','Black pepper and turmeric'],
    steps:['Wilt the spinach in the olive oil, 60 seconds.','Add beaten eggs, cook soft.','Top with avocado, turmeric and a heavy grind of pepper.'] },
  { phase:1, name:'Garlic Shot', time:'2 min', why:'Allicin supports vascular flexibility. Crushing and resting is what activates it.',
    ingredients:['1 clove raw garlic, crushed','Juice of half a lemon','1 tsp olive oil','Splash of water'],
    steps:['Crush the garlic and let it sit 10 minutes — this is the step that matters.','Mix with lemon, oil and water.','Take it in one go, with food if it is harsh.'] },
  { phase:1, name:'Hydration Base', time:'2 min', why:'Plain water without electrolytes passes straight through. A pinch of salt keeps it in circulation.',
    ingredients:['1L filtered water','Pinch of sea salt','Juice of one lemon','Optional: 3 mint leaves'],
    steps:['Combine in a bottle.','Drink 500ml on waking, the rest before noon.'] },
  { phase:1, name:'Sleep Support Plate', time:'8 min', why:'Magnesium and glycine at dinner deepen the first sleep cycle, where the testosterone pulse lives.',
    ingredients:['150g salmon','Handful of pumpkin seeds','Steamed broccoli','Olive oil','Sea salt'],
    steps:['Pan-sear the salmon 3 minutes per side.','Steam the broccoli 4 minutes.','Plate with olive oil and scatter the seeds.'] },

  /* Phase 2 */
  { phase:2, name:'Collagen Builder Salad', time:'7 min', why:'Vitamin C and the amino acids collagen is assembled from, in the same meal — neither works alone.',
    ingredients:['2 bell peppers, sliced','100g shredded chicken','Handful of pumpkin seeds','Olive oil and lemon','Parsley'],
    steps:['Toss the peppers with oil, lemon and parsley.','Add the chicken and seeds.','Eat within the hour — vitamin C degrades fast once cut.'] },
  { phase:2, name:'Zinc Loaded Skillet', time:'9 min', why:'Zinc is a direct precursor in testosterone synthesis and the mineral most often low in men over 40.',
    ingredients:['150g ground beef','Half an onion','1 clove garlic','Handful of spinach','2 eggs'],
    steps:['Brown the beef with onion and garlic.','Add spinach until wilted.','Crack the eggs in, cover, cook 3 minutes.'] },
  { phase:2, name:'Bone Broth Base', time:'5 min (from stock)', why:'Glycine and proline are the structural amino acids of connective tissue, including the tunica.',
    ingredients:['300ml bone broth','1 tsp miso','Ginger, grated','Spring onion','Black pepper'],
    steps:['Heat the broth, do not boil.','Stir in miso off the heat.','Top with ginger and spring onion.'] },
  { phase:2, name:'Kiwi and Seed Bowl', time:'3 min', why:'Kiwi carries more vitamin C than orange, and the seeds bring the zinc and magnesium alongside it.',
    ingredients:['2 kiwis','2 tbsp Greek yoghurt','1 tbsp pumpkin seeds','1 tbsp walnuts','Cinnamon'],
    steps:['Chop and combine.','Dust with cinnamon.'] },
  { phase:2, name:'Post-Cold Recovery Plate', time:'10 min', why:'Protein and fat right after cold exposure support the rebuild rather than just the stress response.',
    ingredients:['2 sardine fillets','2 boiled eggs','Arugula','Olive oil','Lemon'],
    steps:['Boil the eggs 7 minutes.','Plate on arugula with sardines.','Dress heavily with oil and lemon.'] },

  /* Phase 3 */
  { phase:3, name:'Polyphenol Bomb', time:'4 min', why:'Polyphenols protect nitric oxide from being destroyed before it can act — production is only half the equation.',
    ingredients:['Handful of blueberries','Handful of blackberries','200ml unsweetened green tea, cooled','1 tbsp chia','Squeeze of lemon'],
    steps:['Soak the chia in the tea for 10 minutes.','Add the berries and lemon.'] },
  { phase:3, name:'Sulforaphane Steam', time:'6 min', why:'Sulforaphane switches on your own antioxidant system rather than just donating antioxidants.',
    ingredients:['200g broccoli florets','1 tbsp olive oil','Lemon','Sea salt','Optional: mustard seed powder'],
    steps:['Steam 4 minutes — never boil, the compound leaches into the water.','Dress with oil, lemon and salt.','A pinch of mustard powder restores the enzyme lost to heat.'] },
  { phase:3, name:'Stress-Down Evening Tea', time:'3 min', why:'Chamomile and glycine lower evening cortisol, which is the mechanism behind stress-related difficulty.',
    ingredients:['Chamomile tea bag','1 tsp raw honey','Slice of ginger','Squeeze of lemon'],
    steps:['Steep 5 minutes.','Drink an hour before bed, as part of the wind-down.'] },
  { phase:3, name:'Omega-3 Plate', time:'8 min', why:'Omega-3s change the composition of the cell membranes themselves, making the endothelium more responsive.',
    ingredients:['150g mackerel or herring','Red cabbage, shredded','Olive oil','Apple cider vinegar','Walnuts'],
    steps:['Pan-sear the fish 3 minutes per side.','Toss the cabbage with oil and vinegar.','Scatter walnuts over the top.'] },
  { phase:3, name:'Detox Green Juice', time:'4 min', why:'Nitrates, chlorophyll and gingerols with nothing competing for absorption.',
    ingredients:['2 handfuls spinach','1 cucumber','Thumb of ginger','1 green apple','Juice of one lemon'],
    steps:['Blend with 150ml water.','Drink immediately — the nitrates degrade on standing.'] },

  /* Phase 4 */
  { phase:4, name:'Testosterone Breakfast', time:'7 min', why:'Cholesterol is the literal precursor molecule for testosterone. Low-fat diets cap production.',
    ingredients:['3 whole eggs','1 tbsp butter','Handful of mushrooms','Avocado','Sea salt'],
    steps:['Fry the mushrooms in butter.','Add eggs, cook to your preference.','Serve with avocado and salt.'] },
  { phase:4, name:'Boron Trail Mix', time:'2 min', why:'Boron lowers SHBG, which frees testosterone you already produce rather than making more.',
    ingredients:['Handful of raisins','Handful of almonds','2 Brazil nuts','1 square dark chocolate 85%'],
    steps:['Combine. Two Brazil nuts, not five — selenium has a narrow window.'] },
  { phase:4, name:'Pre-Lift Fuel', time:'3 min', why:'Beets 90 minutes before heavy work measurably improves output, and output drives the hormonal response.',
    ingredients:['200ml beet juice','Pinch of sea salt','Squeeze of lemon','Black coffee, optional'],
    steps:['Combine and drink 90 minutes before lifting.'] },
  { phase:4, name:'Oyster Night', time:'5 min', why:'The highest zinc density of any food, plus the dopamine precursors that affect desire itself.',
    ingredients:['6 oysters','Lemon','Shallot in red wine vinegar','Black pepper'],
    steps:['Serve raw with lemon and the shallot mignonette.','If raw is not an option, tinned smoked oysters work.'] },
  { phase:4, name:'Fast-Breaking Plate', time:'9 min', why:'Breaking a 14-hour fast with protein and fat rather than carbohydrate keeps insulin low and testosterone favourable.',
    ingredients:['150g steak','2 eggs','Asparagus','Butter','Sea salt'],
    steps:['Sear the steak to your preference, rest it.','Fry the eggs and asparagus in the same pan.'] },

  /* Phase 5 */
  { phase:5, name:'Citrulline Pre-Load', time:'3 min', why:'Citrulline from watermelon survives liver metabolism better than arginine and raises nitric oxide for hours.',
    ingredients:['300g watermelon, with some white rind','Juice of one lime','Pinch of salt','Mint'],
    steps:['Blend, including a little of the white rind — that is where the citrulline concentrates.','Drink 2-3 hours before.'] },
  { phase:5, name:'Performance Stack Drink', time:'4 min', why:'The full pre-encounter nitrate and hydration stack in one glass, timed at 90 minutes.',
    ingredients:['150ml beet juice','150ml watermelon juice','Pinch of sea salt','Squeeze of lemon'],
    steps:['Combine and drink 90 minutes before.','Follow with 500ml plain water.'] },
  { phase:5, name:'Light Pre-Encounter Plate', time:'6 min', why:'Heavy meals divert blood to digestion. This is enough food to avoid a crash without competing.',
    ingredients:['100g white fish or chicken','Rocket','Olive oil','Lemon','Handful of pistachios'],
    steps:['Grill the protein 4 minutes.','Serve on rocket with oil and lemon.','Eat at least 3 hours before.'] },
  { phase:5, name:'Recovery Shake', time:'2 min', why:'Rebuilding after high-intensity training weeks — pelvic tissue adapts during recovery, not during work.',
    ingredients:['200ml whole milk or kefir','1 banana','1 tbsp almond butter','Cinnamon','Pinch of salt'],
    steps:['Blend 30 seconds.'] },
  { phase:5, name:'Dark Chocolate Flavanol Hit', time:'1 min', why:'Cocoa flavanols acutely improve flow-mediated dilation — a direct measure of vascular responsiveness.',
    ingredients:['20g dark chocolate, 85% or higher','5 almonds','Black coffee or green tea'],
    steps:['Eat slowly, 2 hours before. Below 70% cocoa it is mostly sugar and works against you.'] },

  /* Phase 6 */
  { phase:6, name:'The Ten Minute Default', time:'8 min', why:'The meal you will still cook on your worst week. Maintenance beats optimisation you abandon.',
    ingredients:['3 eggs','Any leafy green','Olive oil','Whatever protein is in the fridge','Salt and pepper'],
    steps:['Wilt the greens in oil.','Add protein and eggs.','Done. No decisions required.'] },
  { phase:6, name:'Weekly Beet Ritual', time:'4 min', why:'Twice a week is the maintenance dose for nitrates. Daily is unnecessary once adapted.',
    ingredients:['1 raw beet','1 apple','Ginger','Lemon','Water'],
    steps:['Blend and drink. Twice a week, not daily.'] },
  { phase:6, name:'Sunday Fish', time:'10 min', why:'Two fatty fish meals a week maintains the omega-3 membrane composition you built in Phase 3.',
    ingredients:['2 salmon fillets','Lemon','Olive oil','Any green vegetable','Sea salt'],
    steps:['Bake at 200°C for 10 minutes.','Serve with the vegetable and plenty of oil.'] },
  { phase:6, name:'Maintenance Mineral Mix', time:'2 min', why:'Zinc, selenium, magnesium and boron in one handful, three times a week.',
    ingredients:['Pumpkin seeds','2 Brazil nuts','Almonds','Raisins','Dark chocolate 85%'],
    steps:['Mix a jar of it. Keep it where you will actually reach for it.'] },
  { phase:6, name:'The Reset Broth', time:'6 min', why:'For the annual thirty-day reset, or any week you feel the baseline slipping.',
    ingredients:['400ml bone broth','Garlic','Ginger','Turmeric','Black pepper','Greens'],
    steps:['Simmer the aromatics in the broth 5 minutes.','Add greens at the end.','Twice daily for the first week of a reset.'] }
];

const SHOPPING = {
  1:['Beets','Spinach','Arugula','Walnuts','Extra virgin olive oil','Eggs','Wild salmon','Blueberries','Garlic','Pumpkin seeds','Green tea','Avocado','Brazil nuts','Lemons','Ginger','Turmeric','Broccoli','Sea salt'],
  2:['Bell peppers','Kiwi','Beef','Oysters or tinned shellfish','Pumpkin seeds','Bone broth','Greek yoghurt','Eggs','Sardines','Almonds','Spinach','Cashews','Hard cheese','Lentils','Strawberries','Olive oil'],
  3:['Blueberries','Blackberries','Red cabbage','Broccoli','Brussels sprouts','Mackerel or herring','Green tea','Chamomile tea','Walnuts','Chia seeds','Cucumber','Green apples','Ginger','Dark chocolate 85%','Olive oil','Turmeric'],
  4:['Eggs','Butter','Grass-fed beef or steak','Oysters','Raisins','Almonds','Brazil nuts','Avocado','Mushrooms','Asparagus','Beet juice','Dark chocolate','Whole milk yoghurt','Sea salt','Garlic'],
  5:['Watermelon','Beet juice','Cucumber','Rocket','Pistachios','White fish or chicken','Kefir or whole milk','Bananas','Almond butter','Dark chocolate 85%','Limes','Mint','Pumpkin seeds','Sea salt'],
  6:['Eggs','Leafy greens','Olive oil','Salmon','Beets','Apples','Pumpkin seeds','Brazil nuts','Almonds','Raisins','Bone broth','Garlic','Ginger','Turmeric','Dark chocolate 85%']
};

const ARTICLES = [
  { w:1, t:'How sleep affects your erection (and the one habit that fixes it)', lead:'Most of your testosterone is released in a single window you probably sabotage every night.',
    body:['Testosterone is not produced evenly across the day. The largest pulse happens during the first deep sleep cycle, roughly 60 to 90 minutes after you fall asleep. Men who sleep five hours a night show testosterone levels comparable to men ten to fifteen years older.','The habit that fixes it is not more hours. It is a fixed bedtime. A consistent lights-out time within a 30-minute window trains your circadian system to deliver deep sleep early, when it counts. Sleeping eight hours on a schedule that moves by two hours nightly gives you the hours without the architecture.','Start tonight. Pick the time, hold it for a week, and watch your morning erections. That is the feedback loop.'] },
  { w:2, t:'The 5 foods destroying your testosterone without you knowing', lead:'None of them are obviously unhealthy. That is exactly why they persist.',
    body:['Industrial seed oils — canola, soybean, corn — are high in omega-6 linoleic acid, which in excess drives inflammation and has been associated with reduced testicular function. They are in almost every restaurant meal and packaged food.','Alcohol suppresses the overnight testosterone pulse for roughly 24 hours, and beer adds a phytoestrogen load from hops on top. Sugar creates the insulin resistance that tracks directly with low testosterone. Low-fat products remove the cholesterol that testosterone is literally synthesised from. And soy protein isolate, at the concentrations found in bars and shakes, is a genuine concern in a way that whole soy foods are not.','You do not need to eliminate all five forever. You need to know which ones you eat daily without noticing.'] },
  { w:3, t:'Why your morning erection is the best health indicator you have', lead:'It is not about sex. It is a nightly pressure test your body runs on itself.',
    body:['During REM sleep, healthy men have three to five erections. This is not arousal — it is an automatic process that oxygenates the tissue and tests the whole system: nerves, arteries, hormones and the tunica that holds pressure.','When morning erections disappear, it is almost always vascular or hormonal rather than psychological, because psychology is not operating while you sleep. This is why it is the most useful single marker you can track, and why every check-in in this protocol asks about it.','Track it honestly and without judgement. It will move before anything else does.'] },
  { w:4, t:'The truth about Kegel exercises — are you doing them wrong?', lead:'Most men are. And the most common error makes things worse, not just slower.',
    body:['The pelvic floor is a hammock of muscle supporting the base of the penis. Contracting it increases the pressure that keeps blood trapped. That much is widely known. What is not is that a large share of men with erectile difficulty have a pelvic floor that is too tight, not too weak.','A tight pelvic floor restricts the very circulation you are trying to improve. If you clench your glutes or hold your breath during a Kegel, you are recruiting the wrong muscles and reinforcing the tightness. This is why the protocol pairs Kegels with reverse Kegels and hip flexor work from the first week.','Ten clean repetitions beat fifty forced ones. Quality, not volume.'] },
  { w:5, t:'How stress literally shrinks your performance (and how to reverse it)', lead:'Cortisol and testosterone compete for the same raw material.',
    body:['Both hormones are synthesised from pregnenolone. When the body perceives sustained threat, it prioritises cortisol production, and the raw material spent there is not available for testosterone. This is not a metaphor — it is a resource allocation problem in a shared pathway.','There is a second mechanism. An erection is a parasympathetic event; anxiety is sympathetic. The two systems are mutually exclusive by design. This is why performance pressure is self-fulfilling, and why breathing work is not a soft add-on to this protocol but a mechanical intervention.','A longer exhale than inhale is the fastest reliable way to shift states. Four seconds in, eight out, for five minutes.'] },
  { w:6, t:'Cold showers and erections — what the science actually says', lead:'The benefit is not in the cold. It is in what happens 60 seconds after.',
    body:['Cold exposure causes rapid vasoconstriction. That is not the useful part. The useful part is the rebound vasodilation that follows, which is stronger than baseline and trains the vessels to respond quickly on demand.','That responsiveness is precisely what an erection requires — a fast, large increase in blood flow triggered by a signal. Repeated exposure improves the speed and magnitude of that response. Thirty to ninety seconds is enough; longer is mostly discomfort with diminishing return.','One timing caveat: do not do this immediately before sex. The constriction phase is still active. Use it hours earlier, or on non-encounter days.'] },
  { w:7, t:'The connection between gut health and sexual performance', lead:'A meaningful share of your nitric oxide production starts in your mouth and gut, not your blood vessels.',
    body:['Dietary nitrate from vegetables is converted to nitrite by bacteria on your tongue, then to nitric oxide further down. This is why antibacterial mouthwash has been shown to measurably raise blood pressure — it kills the bacteria doing the first step.','Beyond that, gut inflammation drives systemic inflammation, and systemic inflammation degrades the endothelial lining of every vessel including the small ones that matter here. Fibre, fermented food and reduced ultra-processed intake are vascular interventions, even though they never get described that way.','If you use antibacterial mouthwash daily, that is a free thing to change this week.'] },
  { w:8, t:'Why most men over 40 are zinc deficient (and what to do about it)', lead:'Zinc sits directly in the testosterone synthesis pathway, and modern diets are thin on it.',
    body:['Soil depletion, reduced red meat and shellfish intake, and higher grain consumption have combined to push a large share of middle-aged men into marginal zinc status. Marginal, not clinical — enough to matter hormonally without ever showing on a routine blood panel.','Oysters are the densest source by a wide margin. Beef, pumpkin seeds and lentils cover it adequately. Absorption drops sharply in the presence of calcium, so separating your dairy from your zinc-heavy meal is worth doing.','Food beats supplementation here because it arrives with the cofactors. You do not need a bottle for this.'] },
  { w:9, t:'How 10 minutes of walking changes your blood flow', lead:'The timing matters more than the duration.',
    body:['Post-meal glucose spikes are when vascular damage actually accumulates. Ten minutes of walking immediately after eating measurably flattens that curve — more effectively than a longer walk at a different time.','The mechanism is simple: contracting muscle takes glucose out of the blood without needing insulin. You are borrowing a pathway that does not depend on the one that has degraded.','Three ten-minute walks after three meals beats one thirty-minute walk in the evening, for this specific purpose.'] },
  { w:10, t:'The worst sleeping position for erectile function', lead:'Sleeping on your stomach compresses exactly what you are trying to decompress.',
    body:['Prone sleeping puts sustained pressure on the perineum and pelvis for hours at a time, restricting the pudendal artery. It also forces cervical rotation, which fragments sleep quality and therefore the deep-sleep hormonal window.','Side sleeping is the best compromise for most men — it keeps pressure off the perineum and supports airway patency, which matters if snoring or apnoea is in the picture. Sleep apnoea, incidentally, is one of the most under-diagnosed causes of erectile difficulty in men over 45.','If you snore heavily and wake unrested despite adequate hours, that is worth raising with a doctor.'] },
  { w:11, t:'Alcohol and erections — where is the real line?', lead:'The threshold is lower than most men assume, and the cost lasts longer.',
    body:['Acutely, alcohol is a central nervous system depressant that dulls the nerve signalling an erection depends on. Two drinks is noticeable for most men; four is decisive. That part is familiar.','What is less known is the 24-hour tail. Alcohol suppresses the overnight testosterone pulse, and it directly inhibits collagen synthesis — which matters enormously during the rebuild phase of this protocol. One heavy night costs a full day of progress.','If you drink, cluster it rather than spreading it. The recovery cost of one occasion is lower than repeated small hits across the week.'] },
  { w:12, t:'How to read your body signals during the protocol', lead:'Four markers tell you almost everything. The rest is noise.',
    body:['Morning erections tell you about vascular and hormonal function. Sleep quality tells you whether the hormonal window is intact. Energy on waking tells you whether recovery is happening. And time to firmness tells you about nitric oxide availability specifically.','Watch those four. Ignore day-to-day fluctuation — a bad day means nothing, a bad fortnight means something. Adaptation in vascular tissue is measured in weeks.','If three of the four are moving in the right direction, the protocol is working even if the fourth lags.'] },
  { w:13, t:'The role of nitric oxide in your erection, simplified', lead:'One molecule sits at the centre of the entire mechanism.',
    body:['When arousal occurs, nerve endings release nitric oxide into the tissue. It signals the smooth muscle in the arteries to relax, which lets blood rush in. The tunica then traps that blood under pressure. That is the whole sequence.','ED medication does not create nitric oxide. It blocks the enzyme that breaks down the downstream signal, so the effect lasts longer. Dietary nitrates work from the other end — by increasing how much nitric oxide is available in the first place.','This is why beets, arugula and spinach appear throughout this protocol, and why polyphenols matter: they protect the nitric oxide you produce from being destroyed before it acts.'] },
  { w:14, t:'Why your erection is stronger in the morning, and how to use that', lead:'Testosterone peaks at dawn. Most men schedule sex at exactly the wrong time.',
    body:['Testosterone follows a daily curve that peaks in the early morning and declines through the day, reaching its lowest point in the evening. Combine that with accumulated fatigue, alcohol and stress by 10pm, and evening is close to the worst available window physiologically.','You cannot always reschedule your life around this. But knowing it explains a lot of inconsistency men interpret as unreliability, and morning is worth deliberately using when it is available.','It also explains why the first successes during this protocol usually show up in the morning.'] },
  { w:15, t:'Porn and erectile dysfunction — what the research says', lead:'The mechanism is specific, and so is the fix.',
    body:['The concern is not moral. It is that high-novelty, high-intensity, purely visual stimulation trains the arousal response to a stimulus that a real partner cannot replicate. Some men then find themselves unable to reach the same arousal threshold in person.','The evidence base is still developing and the effect is not universal. But it is well documented enough that if you can achieve a firm erection alone and not with a partner, this is the first thing to examine — before assuming a vascular cause.','A structured break of several weeks, combined with the arousal control work in Phase 4, is the usual approach.'] },
  { w:16, t:'The 3-minute breathing technique that lowers cortisol', lead:'The ratio matters more than the depth.',
    body:['An exhale longer than the inhale triggers the parasympathetic shift. The vagus nerve responds to the pressure changes in the chest, slowing heart rate and lowering circulating stress hormones. Four seconds in, eight seconds out, is the simplest reliable ratio.','Three minutes is enough to produce a measurable change. It is not meditation and it requires no belief in anything — it is a mechanical intervention on an autonomic system.','Use it before sleep, before sex, and any time you notice your jaw or shoulders tightening.'] },
  { w:17, t:'How to talk to your partner about what you are doing', lead:'The conversation most men avoid is usually the one that removes the pressure.',
    body:['You do not have to frame it as a problem being fixed. Framing it as something you are doing for your health, energy and sleep is accurate and lands better. Most partners notice the effort and respond to it.','The practical benefit is that performance anxiety feeds on secrecy. If she knows you are working on something over months, a single difficult night stops being a verdict and becomes a data point.','If you would rather say nothing, that is legitimate too. This protocol is entirely discreet. But secrecy has a cost worth being aware of.'] },
  { w:18, t:'Hydration and erections — the number most men get wrong', lead:'An erection is a hydraulic event. Blood volume is the fluid.',
    body:['Dehydration of only 2% measurably reduces plasma volume and thickens blood, which impairs flow through the smallest vessels first — exactly the ones involved here. Most men walk around at 2 to 3% without any sense of thirst.','Three litres across the day is the working target for most men, front-loaded so the bulk is done by early evening. Plain water without any electrolytes passes through quickly; a pinch of salt in the first litre keeps more of it in circulation.','Finish early. Being up at 3am to urinate costs you the deep sleep that matters more.'] },
  { w:19, t:'Why sitting all day is killing your erection', lead:'The pressure is on the exact artery you depend on.',
    body:['Prolonged sitting compresses the perineum, restricting the pudendal artery — the main blood supply to the penis. It also shortens the hip flexors, which further compresses the vessels feeding the pelvis, and it reduces the muscular pumping that returns blood from the lower body.','Men who sit more than eight hours a day show measurably higher rates of erectile difficulty independent of weight and fitness. The intervention costs nothing: stand for two minutes every 45.','The couch stretch from Phase 1 addresses the second half of the problem. Together they neutralise most of the damage.'] },
  { w:20, t:'The supplement industry secret about testosterone boosters', lead:'Almost none of them raise testosterone. The ones that do, do it by fixing a deficiency.',
    body:['The large majority of products marketed as testosterone boosters have no effect in men with adequate nutrient status. Where studies show benefit, it is usually in men who were deficient in zinc, magnesium or vitamin D — correcting a deficiency, not enhancing normal function.','This is why this protocol contains no supplements. Everything it uses is food, and food delivers nutrients with the cofactors that improve absorption. Two Brazil nuts and a handful of pumpkin seeds cover selenium and zinc for a day.','If you suspect a genuine deficiency, a blood test is worth far more than a bottle.'] },
  { w:21, t:'How your phone screen at night affects your hormones', lead:'It is not the content. It is the wavelength and the timing.',
    body:['Blue-weighted light in the evening suppresses melatonin release, which delays the onset of deep sleep. Since the largest testosterone pulse happens in the first deep sleep block, delaying that block compresses or displaces the pulse.','Night mode helps less than reducing brightness, and both help less than simply not using the screen. Sixty minutes before bed is the useful threshold.','This is the highest-leverage change available to most men in Phase 1, and it costs nothing but habit.'] },
  { w:22, t:'The real reason Viagra stops working over time', lead:'The drug does not stop working. The underlying problem keeps progressing.',
    body:['PDE5 inhibitors amplify a signal that already exists — they do not create nitric oxide and they do not repair tissue. If the underlying vascular degradation continues, the amplification has less and less to work with.','This is also why the dose tends to climb over years. Nothing addressed the cause; the volume knob just got turned up. Meanwhile the tunica continues losing elasticity and the endothelium continues degrading.','A structural protocol works the other way: slower, but it changes what the drug would otherwise be compensating for.'] },
  { w:23, t:'Exercise and erections — the minimum effective dose', lead:'More is not better. There is a point where it reverses.',
    body:['Moderate aerobic work builds capillary density and improves endothelial function. Heavy compound lifting produces an acute androgenic response. Both help. But excessive endurance training raises cortisol chronically and suppresses testosterone — marathon runners routinely show lower levels than sedentary controls.','The effective dose is modest: 15 to 20 minutes of zone 2 most days, plus two or three short heavy sessions a week. That is it.','If you are training hard and your morning erections got worse, you are past the useful dose.'] },
  { w:24, t:'How sugar affects your blood vessels', lead:'Glycation is the mechanism, and it is slow, cumulative and mostly silent.',
    body:['Excess glucose in the bloodstream binds to proteins in a process called glycation, producing compounds that stiffen collagen and damage the endothelial lining. In the penis, stiffened collagen in the tunica means it can no longer stretch and seal properly — which is how venous leak develops.','This is the same mechanism behind diabetic complications, which is why erectile difficulty is frequently the first symptom of undiagnosed diabetes, often appearing years before diagnosis.','The post-meal walk and the removal of refined sugar in Phase 1 are aimed directly at this.'] },
  { w:25, t:'The psychology of sexual confidence — what actually works', lead:'Confidence follows evidence. It cannot be installed in advance.',
    body:['Trying to feel confident before you have reason to is why affirmation approaches fail. What works is accumulating small, verifiable evidence — a firmer morning erection, a longer session, a night that went well — until the expectation shifts on its own.','This is the real reason the weekly check-ins exist in this protocol. They force you to record evidence you would otherwise forget, because the brain weights recent failures far more heavily than gradual improvement.','Read your Week 1 notes at Week 12. The gap is usually larger than you remember.'] },
  { w:26, t:'Life after the protocol — how to maintain results forever', lead:'The programme was designed to end. Maintenance is a different, lighter thing.',
    body:['Vascular adaptation is maintained at roughly a third of the effort it took to build. Once the capillary density and endothelial function are there, they persist with far less input — provided the destructive inputs do not return in full.','Your maintenance floor is small: water on waking, a daily walk, a Kegel set three times a week, twice-weekly cold exposure, and the fixed bedtime. Ten minutes a day. On top of that, an annual thirty-day repeat of Phase 1 keeps the baseline from drifting.','The men who keep results are not the most disciplined. They are the ones who reduced it to something small enough to survive a bad month.'] }
];

const FAQ = {
  'Phase 1 — Foundation (Days 1-30)':[
    ['Day 3 and I feel nothing. Is this normal?','Yes. The first noticeable changes usually appear between days 5 and 10, and they are subtle — a partial morning erection, better energy on waking. Your body is still in the initial adjustment phase. Keep following the daily protocol.'],
    ['I woke up with a partial erection. Is that the protocol working?','Very likely. Partial morning erections in the first two weeks are one of the earliest signs, and they tend to strengthen from there. This is why every check-in asks about them.'],
    ['Can I drink alcohol during the protocol?','Minimise it. Alcohol directly impacts blood flow and suppresses the overnight testosterone pulse for around 24 hours. If you do drink, keep it to one occasion a week rather than spreading it out.'],
    ['Do I need to buy supplements?','No. The protocol uses common foods and techniques only. Nothing in it requires a bottle.'],
    ['How long should a Kegel session take?','Under two minutes. If you are going much longer you are probably overworking a muscle that in most men is already too tight.'],
    ['I keep forgetting the water first thing. Any trick?','Fill the glass the night before and put it where you will physically bump into it. Removing the decision is more reliable than remembering.'],
    ['I missed two days. Should I double up?','No. Resume at the current day. The protocol works on consistency, not accumulation, and doubling up on techniques risks soreness.'],
    ['Is the cold shower necessary in Phase 1?','It does not start until Phase 2. Phase 1 is about hydration, sleep, inflammation and finding the pelvic floor.'],
    ['My hips are sore from the stretches. Is that expected?','Mild stiffness the first week is normal, especially if you sit a lot. Sharp or joint pain is not — back off the range and build slowly.']
  ],
  'Phase 2 — Rebuild (Days 31-60)':[
    ['The cold water is genuinely unpleasant. Can I skip it?','You can, but it is one of the higher-yield items in this phase. Start at 15 seconds rather than skipping entirely, and focus on slow nasal breathing through it.'],
    ['How cold does the water need to be?','Whatever your tap gives is enough. You are not trying to shock yourself — you are training a dilation response. Gasping means it is too much.'],
    ['I do not eat fish. What replaces it?','Walnuts, flaxseed, chia and pasture-raised eggs cover omega-3s reasonably. For zinc, use beef, pumpkin seeds and lentils.'],
    ['Nothing has changed since Phase 1. Should I be worried?','Phase 2 is tissue rebuilding, which is the slowest-feeling part of the protocol. Judge it at day 60, not day 40. Collagen turnover takes weeks.'],
    ['Can I do the cold exposure in the morning and the Kegels at night?','Yes. Nothing in the protocol depends on doing everything at once. Spread it however fits your day.'],
    ['Is a cold plunge better than a cold shower?','Marginally, and not enough to matter. The shower is what you will actually do daily, which makes it the better option.'],
    ['I get lightheaded during the cold exposure.','Stop and step out. Keep the breathing slow and nasal next time, and shorten the duration. Lightheadedness means the stress response is outrunning the benefit.'],
    ['How much protein do I actually need?','Enough that tissue repair is not limited — roughly 1.6g per kilo of bodyweight is a reasonable working target, front-loaded toward the morning.']
  ],
  'Phase 3 — Protect (Days 61-90)':[
    ['My progress seems to have plateaued.','Phase 3 is consolidation rather than acceleration. It protects what Phases 1 and 2 built. The next clear jump usually comes in Phase 4 when hormonal work begins.'],
    ['How much zone 2 cardio is enough?','Fifteen to twenty minutes most days. Going harder turns it into a stress event, which raises cortisol and works against you.'],
    ['I am under a lot of work stress right now.','Then the breathing work and the wind-down hour are the most important items on your list this phase, above the food. Cortisol will cap everything else.'],
    ['Do I have to give up coffee?','No. Keep it before 2pm. Late caffeine fragments deep sleep even when you fall asleep fine.'],
    ['Is green tea as good as the protocol suggests?','It is useful, not magic. The EGCG protects nitric oxide from degradation. Two cups a day between meals is the practical dose.'],
    ['Can I eat fruit? It has sugar.','Yes. Whole fruit comes with fibre and polyphenols and behaves nothing like refined sugar. Fruit juice is a different matter.'],
    ['I cannot manage a full hour of wind-down.','Thirty minutes still helps. The last thing before sleep matters more than the total duration.'],
    ['My sleep got worse this phase.','Look at evening light and late caffeine first. Those account for the large majority of cases.']
  ],
  'Phase 4 — Reactivate (Days 91-120)':[
    ['Should I do the edging work every day?','No. Two to three sessions a week is the useful dose. Daily practice tends to produce tension rather than control.'],
    ['I lose the erection during the stop phase.','Common and expected early on. Shorten the stop to 15 seconds and build up. It improves within a couple of weeks.'],
    ['Is intermittent fasting safe for me?','The version here is a 12 to 14 hour overnight window, which is modest. If you have diabetes or take medication with food, check with your doctor before changing meal timing.'],
    ['How heavy should the lifting be?','Heavy enough that 5 to 8 repetitions is genuinely hard, with long rests. Fifteen minutes is enough. This is about hormonal response, not volume.'],
    ['Does the squeeze technique hurt?','It should not. Firm, brief pressure just below the head for about five seconds. If there is pain, you are pressing far too hard.'],
    ['I still have no morning erections at Day 100.','Look at alcohol and sleep before anything else — they explain the majority of cases at this stage. If both are genuinely clean, this is worth discussing with a doctor.'],
    ['Can I combine this with training I already do?','Yes, provided total load stays reasonable. If morning erections worsen while training hard, that is your signal to pull back.']
  ],
  'Phase 5 — Amplify (Days 121-150)':[
    ['How far before sex should I do the pre-encounter stack?','Nitrates need about 90 minutes to convert. Water and the walk can be closer. Breathing right before.'],
    ['Should I avoid ejaculating before an encounter?','For most men, yes — 24 to 48 hours beforehand noticeably improves intensity and duration. Test it and see how you respond.'],
    ['My duration has not improved much.','Check whether the limit is arousal or physical fatigue. If your hips and core give out first, train those — most men assume it is arousal when it is not.'],
    ['Is the non-ejaculatory session necessary?','It is the fastest way to build tolerance at high arousal. If it does not suit you, extend the edging sessions instead.'],
    ['Cold exposure right before sex — good idea?','No. The constriction phase is still active. Do it two to three hours earlier or on other days.'],
    ['I feel like I am overtraining the pelvic floor.','Then you probably are. Take two full days off. Tight is not the same as strong, and a tight pelvic floor reduces circulation.']
  ],
  'Phase 6 — Maintain (Days 151-180)':[
    ['What do I actually keep doing after Day 180?','Water on waking, a daily walk, three Kegel sets a week, cold exposure twice a week, and the fixed bedtime. About ten minutes a day.'],
    ['Will I lose the results if I stop?','Not quickly, and not entirely. Vascular adaptation persists at roughly a third of the effort it took to build — provided the destructive inputs do not fully return.'],
    ['Can I repeat the protocol?','Yes. A thirty-day repeat of Phase 1 once a year is the recommended reset.'],
    ['Can I drink normally again?','Reintroduce it deliberately and watch your morning erections for a week. You now have a clean baseline and a reliable personal test — use it.'],
    ['What if things slide?','Repeat two weeks of Phase 1 and two weeks of Phase 4. That recovers most drift. Write the plan down now, while things are good.']
  ],
  'General':[
    ['I am on blood pressure medication. Can I do the protocol?','Talk to your doctor before starting, and specifically mention the beetroot and beet juice. Dietary nitrates lower blood pressure, and combined with BP medication — especially nitrates prescribed for heart conditions — that can drop it too far. Your doctor can tell you what is safe for your particular medication.'],
    ['I have a heart condition or diabetes. Is this suitable?','Bring the protocol to your doctor first. Cold exposure, fasting windows and high-nitrate foods all interact with common cardiac and diabetes treatment. None of this replaces medical advice.'],
    ['My partner does not know I am doing this. Is it discreet?','Yes. It is an app on your phone with no explicit images and no obvious branding. The content reads as health and wellness.'],
    ['Do I need to do it in order?','Yes. Each phase builds on the tissue and habit changes from the one before. Jumping to Phase 4 without the foundation does not work.'],
    ['What if I miss a week?','Resume where you are. Missed days show as missed in your tracker, which is honest feedback rather than punishment. The protocol does not reset.'],
    ['Can I do this alongside ED medication?','Many men do, but discuss it with the doctor who prescribed it — particularly the beet juice, since combining nitrates with PDE5 inhibitors can cause a dangerous drop in blood pressure.'],
    ['Is my data stored anywhere?','No. Everything stays in your browser on this device. Clearing your browser data clears your progress, so avoid doing that.'],
    ['Can I use this on more than one device?','Progress is stored per device and does not sync. Use one device for consistency.'],
    ['The techniques feel awkward at first.','That is normal and it passes within a week or two. Every technique here is a motor skill, and motor skills feel clumsy before they feel automatic.'],
    ['How long until my partner notices?','Most men report the first comments somewhere between weeks 4 and 8, usually about energy and mood before anything else.'],
    ['Is there any point doing this if I am over 65?','Yes. The mechanisms — nitric oxide, capillary density, pelvic floor function, sleep quality — respond at any age. The pace is slower, the direction is the same.'],
    ['What if I have a diagnosed physical cause?','If a doctor has identified a structural or nerve-related cause, follow their guidance. This protocol addresses vascular, hormonal and functional factors; it does not treat structural damage.']
  ]
};
